// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArw86SaevJ30RD8QQwXZ7O5XNVfecBgrw',
    appId: '1:1042997532071:web:0276763c9900fe5af55282',
    messagingSenderId: '1042997532071',
    projectId: 'n-near-school-n',
    authDomain: 'n-near-school-n.firebaseapp.com',
    storageBucket: 'n-near-school-n.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTtMED-uQmJ2mk8Us81ZA3f28yYvaQOgM',
    appId: '1:1042997532071:android:62d6b9028035957af55282',
    messagingSenderId: '1042997532071',
    projectId: 'n-near-school-n',
    storageBucket: 'n-near-school-n.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbb_eTX4ZdBo6wPSglBrQVTT7F9ROnsxs',
    appId: '1:1042997532071:ios:26994a311f400d09f55282',
    messagingSenderId: '1042997532071',
    projectId: 'n-near-school-n',
    storageBucket: 'n-near-school-n.appspot.com',
    iosBundleId: 'com.example.nearSchool',
  );

}